services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      # DATABASE_URL: 'mysql://root:rootpw@db:3306/vrillar'
      DATABASE_HOST=db
      DATABASE_PORT=3306
      DATABASE_USERNAME=root
      DATABASE_PASSWORD=rootpw
      DATABASE_DB_NAME=vrillar
      PORT=8080
    env_file:
      - .env
    ports:
      - '${SERVICE_FORWARD:-8088}:80'
    depends_on:
      - db
    links:
      - db
    networks:
      - vrillar-network
  
  db:
    image: mysql:latest
    restart: always
    ports:
      - '${MYSQL_PORT_FORWARD:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: vrillar
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - vrillar-network
volumes:
  dbdata:
networks:
  vrillar-network:
    driver: bridge
  
